### ISSUE TITLE
proxy de chiffrement : je veux pouvoir chiffrer les pjs avec de nouvelle clé

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/ds_proxy#79]

**Comment by LeSim** [comment]
# pour charger les clés

- on pose un fichier chiffré `keys` qui contient les `clés secondaires` numérotés sur le système de fichier. le fichier est chiffré en symétrique avec une `clé principale`. 
- on lance l'appli avec la `clé principale` en argument pour éviter qu'elle traîne sur le disque

# pour le chiffrement
on prend toujours la dernière clé

# pour le déchiffrement
on a 2 solutions :

1. on tente toutes les clés connues, si aucune ne marche, on estime que le fichier est en clair
  - en théorie un grand nombre de clés possibles
  - on perd en calcul a chaque fois

2. on met un identifiant de la clé dans le header
  - on pourrait dériver l'identifiant de la clé elle-même avec un hash mais ça ferait fuiter de l'info
  - on met le numéro de la clé

la solution 2 semble plus pérenne.

# nombre de clés possible
dans le pire des cas on voudrait 1 clé par dossier. on vise du 10 millions de dossier ans pendant 20 ans (soyons fous), on fait un * 10 pour la sûreté, ça fait du 10 milllions * 20 * 10 = 200 Millions 
du coup, on pourrait partir sur un identifiant sur 32 bit => 4_294_967_296 possibilités

**Comment by tchak** [comment]
2️⃣ :+1:
